### ISSUE TITLE
Is Dual Battery system supported ?

### ISSUE THREAD

**Issue by Sniki** [arcolinux/arcolinux-qtile#1]
Hi,

First, sorry if this is not the right place to ask.

Thanks for the detailed config for Qtile, the work you guys have done is amazing.
I noticed thanks to DistroTube that there is a Qtile ISO of ArcoLinux on one of his videos.
Im on vanilla Arch for now so before i do a clean install of ArcoLinux Qtile, wanted to ask a question as i am relatively new to Python and just started learning:

I have a Lenovo ThinkPad T460s which has two batteries, i have 2 battery widgets (one per each battery), this consumes space on my menu bar and is kind of messy. is it possible to have a single widget on the menu bar to report the percentage of the batteries combined (percentage left from both batteries into one battery bar) like all Desktop Environments and Windows does.
Is this feature already implemented or it needs additional work ?

Thanks in advance !

**Comment by arcolinuxz** [comment]
no idea at all - but Linux would not be Linux if such a widget could not be
created

**Comment by Sniki** [comment]
That’s true.

A script/widget may be needed to calculate capacity of both batteries and report as a single one into one battery widget.

May have to check DE(s) like Gnome, Xfce, KDE on how they calculate and merge capacity of both batteries into one in the menu bar icon.
