### ISSUE TITLE
init functions in qtile/config.py

### ISSUE THREAD

**Issue by CSpencerND** [arcolinux/arcolinux-qtile#2]
Sorry. Not really an issue. Just a curiosity. I don't know how else to ask a question on GitHub.
I'm studying programming and wondering why the init functions in the qtile/config.py. For example, the init_colors():
```
def init_colors():
    return [["#2F343F", "#2F343F"], # color 0
            ["#2F343F", "#2F343F"], # color 1
            ["#c0c5ce", "#c0c5ce"], # color 2
            ["#fba922", "#fba922"], # color 3
            ["#3384d0", "#3384d0"], # color 4
            ["#f3f4f5", "#f3f4f5"], # color 5
            ["#cd1f3f", "#cd1f3f"], # color 6
            ["#62FF00", "#62FF00"], # color 7
            ["#6790eb", "#6790eb"], # color 8
            ["#a9a9a9", "#a9a9a9"]] # color 9


colors = init_colors()
```
Why not just define the list directly like, `colors = [...]`
I guess the question is if there is some logic behind it or if it's just a style decision.
I'm only asking because I'm learning programming and I've never seen this before.

**Comment by arcolinuxz** [comment]
We have zero experience in how to write for qtile

We learn as we go

working with functions and defintions makes everything that belongs
together stick together and you can call it any time you want.

have fun learning

we are all students

**Comment by CSpencerND** [comment]
Erik! Thanks for all the hard work!
